import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { extractEnFrame } from './extractEn';
import { serializeFrame } from './serialize';

/**
 * `tools/build_frame_pairs.py:extract_en` and `extractEnFrame` here are
 * independent reimplementations of the same rules. The training corpus is
 * built with the Python one and `tools/evaluate.py` scores against it, so a
 * divergence between them is invisible at runtime: the model would be trained
 * on frame strings the app never produces.
 *
 * `evaluation/en_frames.python.json` is the Python output over the gold set,
 * regenerated by:
 *   python -c "import json,sys; sys.path.insert(0,'tools'); \
 *     from build_frame_pairs import extract_en, serialize; \
 *     gold=json.load(open('evaluation/gold_sentences.json',encoding='utf-8')); \
 *     print(json.dumps({i['source']: serialize(extract_en(i['source'])) \
 *       for i in gold['en_dv']}, ensure_ascii=False, indent=2))"
 */
const reference = JSON.parse(
  readFileSync(new URL('../../../evaluation/en_frames.python.json', import.meta.url), 'utf-8'),
) as Record<string, string>;

/**
 * OBJECT is deliberately excluded. The Python extractor only fills it from the
 * twelve curated OBJECTS the generator can realize a sentence for; the runtime
 * one is open-vocabulary because it has to cope with whatever a user types.
 * Every other slot must match exactly.
 */
const SHARED_SLOTS = ['SUBJECT', 'ACTION', 'LOCATION', 'TIME', 'TENSE', 'POLARITY', 'REGISTER'];

function sharedSlots(frameString: string): string {
  return frameString
    .split(' | ')
    .filter((part) => SHARED_SLOTS.includes(part.split('=')[0]))
    .join(' | ');
}

describe('Python and TypeScript English extractors agree', () => {
  const sentences = Object.keys(reference);

  it('has a reference frame for every gold sentence', () => {
    expect(sentences.length).toBeGreaterThanOrEqual(20);
  });

  for (const sentence of sentences) {
    it(`matches on: ${sentence}`, () => {
      expect(sharedSlots(serializeFrame(extractEnFrame(sentence)))).toBe(
        sharedSlots(reference[sentence]),
      );
    });
  }
});
