/**
 * Vendor the ONNX Runtime WASM assets into `public/ort/`.
 *
 * Why this exists: `@huggingface/transformers` sets
 *
 *     ONNX_ENV.wasm.wasmPaths = `https://cdn.jsdelivr.net/npm/@huggingface/transformers@${version}/dist/`
 *
 * (see node_modules/@huggingface/transformers/src/backends/onnx.js) unless
 * wasmPaths is already set. That default makes the *first translation* depend on
 * a third-party CDN, which contradicts §1.2 ("no mandatory network call at
 * translation time"), NFR-2 (offline after first load) and NFR-3 (input does not
 * leave the device). `src/core/translate/runner.ts` points wasmPaths at
 * `${BASE_URL}ort/`; this script puts the files there.
 *
 * The output is gitignored and regenerated by `predev` / `prebuild`, so the
 * ~21 MB of WASM is never committed — the repository-weight rule (NFR-13) is
 * about tracked bytes, and vendoring these into git would undo the very thing
 * R-3.13 is cleaning up.
 */

import { copyFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const from = join(root, 'node_modules', '@huggingface', 'transformers', 'dist');
const to = join(root, 'public', 'ort');

// Only the runtime pieces. The bundler handles the library itself; these are the
// files onnxruntime-web fetches by URL at session-create time.
const WANTED = /^ort-.*\.(wasm|mjs)$/;

let files;
try {
  files = readdirSync(from).filter((f) => WANTED.test(f));
} catch {
  console.error(`copy-ort: ${from} not found. Run npm install first.`);
  process.exit(1);
}

if (files.length === 0) {
  console.error(`copy-ort: no ort-*.{wasm,mjs} in ${from}.`);
  console.error('The package layout changed; update WANTED before shipping.');
  process.exit(1);
}

mkdirSync(to, { recursive: true });

let bytes = 0;
for (const file of files) {
  const src = join(from, file);
  copyFileSync(src, join(to, file));
  bytes += statSync(src).size;
  console.log(`copy-ort: ${file}`);
}

console.log(`copy-ort: ${files.length} files, ${(bytes / 1e6).toFixed(1)} MB → public/ort/`);
